default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: projectsapi_development

test:
  <<: *default
  database: projectsapi_test

production:
  <<: *default
  database: projectsapi_production
  username: projectsapi
  password: <%= ENV['PROJECTSAPI_DATABASE_PASSWORD'] %>
